// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForAddSharesToFile implements pgx.CopyFromSource.
type iteratorForAddSharesToFile struct {
	rows                 []AddSharesToFileParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddSharesToFile) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddSharesToFile) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FileID,
		r.rows[0].SharedWith,
	}, nil
}

func (r iteratorForAddSharesToFile) Err() error {
	return nil
}

func (q *Queries) AddSharesToFile(ctx context.Context, arg []AddSharesToFileParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"file_shares"}, []string{"file_id", "shared_with"}, &iteratorForAddSharesToFile{rows: arg})
}
