// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (
    name,
    owner_id,
    parent_folder_id
) VALUES (
    $1, $2, $3
) RETURNING id, name, owner_id, parent_folder_id, created_at
`

type CreateFolderParams struct {
	Name           string      `json:"name"`
	OwnerID        int64       `json:"owner_id"`
	ParentFolderID pgtype.UUID `json:"parent_folder_id"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.Name, arg.OwnerID, arg.ParentFolderID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.ParentFolderID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders
WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, name, owner_id, parent_folder_id, created_at FROM folders
WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.ParentFolderID,
		&i.CreatedAt,
	)
	return i, err
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders
SET 
    name = $2,
    parent_folder_id = $3
WHERE 
    id = $1
RETURNING id, name as filename, owner_id, parent_folder_id, created_at
`

type UpdateFolderParams struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	ParentFolderID pgtype.UUID `json:"parent_folder_id"`
}

type UpdateFolderRow struct {
	ID             uuid.UUID          `json:"id"`
	Filename       string             `json:"filename"`
	OwnerID        int64              `json:"owner_id"`
	ParentFolderID pgtype.UUID        `json:"parent_folder_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (UpdateFolderRow, error) {
	row := q.db.QueryRow(ctx, updateFolder, arg.ID, arg.Name, arg.ParentFolderID)
	var i UpdateFolderRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OwnerID,
		&i.ParentFolderID,
		&i.CreatedAt,
	)
	return i, err
}
