// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBlob(ctx context.Context, arg CreateBlobParams) (Blob, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFileShare(ctx context.Context, arg CreateFileShareParams) (FileShare, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementBlobRefcount(ctx context.Context, id uuid.UUID) (int32, error)
	DeleteBlob(ctx context.Context, id uuid.UUID) error
	DeleteBlobIfUnused(ctx context.Context, id uuid.UUID) (string, error)
	DeleteBlobsByStoragePaths(ctx context.Context, storagePaths []string) error
	DeleteFile(ctx context.Context, id uuid.UUID) error
	DeleteFileShare(ctx context.Context, arg DeleteFileShareParams) error
	DeleteFolder(ctx context.Context, id uuid.UUID) error
	GetBlobByID(ctx context.Context, id uuid.UUID) (Blob, error)
	GetBlobBySha(ctx context.Context, sha256 string) (Blob, error)
	GetBlobIDsInFolderHierarchy(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	GetDeduplicatedUsage(ctx context.Context, ownerID int64) (int64, error)
	GetFileByUUID(ctx context.Context, id uuid.UUID) (File, error)
	GetFilesForUser(ctx context.Context, arg GetFilesForUserParams) ([]GetFilesForUserRow, error)
	GetFilesForUserCount(ctx context.Context, arg GetFilesForUserCountParams) (int64, error)
	GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	IncrementBlobRefcount(ctx context.Context, id uuid.UUID) (int32, error)
	IncrementFileDownloadCount(ctx context.Context, id uuid.UUID) error
	ListAllFiles(ctx context.Context, arg ListAllFilesParams) ([]ListAllFilesRow, error)
	ListFilesByOwner(ctx context.Context, arg ListFilesByOwnerParams) ([]ListFilesByOwnerRow, error)
	ListFilesForUser(ctx context.Context, arg ListFilesForUserParams) ([]ListFilesForUserRow, error)
	ListFilesSharedWithUser(ctx context.Context, arg ListFilesSharedWithUserParams) ([]File, error)
	//---------------------------
	ListFolderContents(ctx context.Context, arg ListFolderContentsParams) ([]ListFolderContentsRow, error)
	ListOtherUsers(ctx context.Context, id int64) ([]ListOtherUsersRow, error)
	ListRootContents(ctx context.Context, arg ListRootContentsParams) ([]ListRootContentsRow, error)
	ListUsersWithAccessToFile(ctx context.Context, fileID uuid.UUID) ([]ListUsersWithAccessToFileRow, error)
	UpdateBlobRefcount(ctx context.Context, arg UpdateBlobRefcountParams) error
	UpdateFilename(ctx context.Context, arg UpdateFilenameParams) (File, error)
	UpdateFolder(ctx context.Context, arg UpdateFolderParams) (UpdateFolderRow, error)
	UserExists(ctx context.Context, id int64) (bool, error)
	UserHasAccess(ctx context.Context, arg UserHasAccessParams) (bool, error)
	UserOwnsBlob(ctx context.Context, arg UserOwnsBlobParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
