export const mimeTypeOptions = [
	{ value: 'folder/folder', label: 'Folder' },
	{ value: 'application/pdf', label: 'PDF Document' },
	{ value: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', label: 'Word Document (.docx)' },
	{ value: 'application/vnd.ms-powerpoint', label: 'PowerPoint Presentation (.ppt)' },
	{ value: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', label: 'PowerPoint Presentation (.pptx)' },
	{ value: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', label: 'Excel Spreadsheet (.xlsx)' },
	{ value: 'text/plain', label: 'Text File' },
	{ value: 'image/jpeg', label: 'JPEG Image' },
	{ value: 'image/png', label: 'PNG Image' },
	{ value: 'video/mp4', label: 'MP4 Video' },
	{ value: 'audio/mpeg', label: 'MP3 Audio' },
	{ value: 'image/gif', label: 'GIF Image' },
	{ value: 'application/zip', label: 'ZIP Archive' },
	{ value: 'application/x-rar-compressed', label: 'RAR Archive' },
	{ value: 'application/x-tar', label: 'TAR Archive' },
	{ value: 'text/html', label: 'HTML Document' },
	{ value: 'text/css', label: 'CSS Stylesheet' },
	{ value: 'application/javascript', label: 'JavaScript File' },
	{ value: 'application/json', label: 'JSON File' },
	{ value: 'application/xml', label: 'XML File' },
	{ value: 'text/html', label: 'HTML Document' },
	{ value: 'text/css', label: 'CSS Stylesheet' },
	{ value: 'application/javascript', label: 'JavaScript File' },
	{ value: 'application/json', label: 'JSON File' },
	{ value: 'application/xml', label: 'XML File' },
	{ value: 'image/webp', label: 'WebP Image' },
	{ value: 'image/svg+xml', label: 'SVG Vector Image' },
	{ value: 'image/bmp', label: 'Bitmap Image' },
	{ value: 'audio/wav', label: 'WAV Audio' },
	{ value: 'audio/aac', label: 'AAC Audio' },
	{ value: 'video/x-msvideo', label: 'AVI Video' },
	{ value: 'video/quicktime', label: 'MOV Video' },
];
